version: '3.7'

services:
    web:
        build: .
        container_name: rest-api
        volumes:
            - ./:/home/rest-api
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        links:
            - mongo

    mongo:
        image: mongo
        restart: always
        container_name: database-api
        ports:
            - "27017:27017"